language: swift

branches:
 only:
 - master

xcode_project: Records.xcodeproj
xcode_scheme: Records
osx_image: xcode9
xcode_sdk: iphonesimulator11.0

script: 
 - xcodebuild -scheme Records -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0' test
 