language: swift

branches:
 only:
 - master

xcode_project: Records.xcodeproj
osx_image: xcode9.3

before_install:
  - brew install sourcery

script: 
 - xcodebuild -scheme Records -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.3' test
